In [12]:
import pandas as pd
import random 
import numpy as np

In [13]:
%pip install scikit-learn

Requirement already satisfied: scikit-learn in C:\Users\UNB\AppData\Local\Programs\Python\Python312\Lib\site-packages (1.8.0)
Requirement already satisfied: numpy>=1.24.1 in C:\Users\UNB\AppData\Local\Programs\Python\Python312\Lib\site-packages (from scikit-learn) (2.1.0)
Requirement already satisfied: scipy>=1.10.0 in C:\Users\UNB\AppData\Local\Programs\Python\Python312\Lib\site-packages (from scikit-learn) (1.17.1)
Requirement already satisfied: joblib>=1.3.0 in C:\Users\UNB\AppData\Local\Programs\Python\Python312\Lib\site-packages (from scikit-learn) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.2.0 in C:\Users\UNB\AppData\Local\Programs\Python\Python312\Lib\site-packages (from scikit-learn) (3.6.0)
Note: you may need to restart the kernel to use updated packages.

## Importar Base de Dados

In [14]:
dataset = pd.read_csv('census.csv')

In [15]:
dataset.describe()

,age,final-weight,education-num,capital-gain,capital-loos,hour-per-week
count,32561.000000,3.256100e+04,32561.000000,32561.000000,32561.000000,32561.000000
mean,38.581647,1.897784e+05,10.080679,1077.648844,87.303830,40.437456
std,13.640433,1.055500e+05,2.572720,7385.292085,402.960219,12.347429
min,17.000000,1.228500e+04,1.000000,0.000000,0.000000,1.000000
25%,28.000000,1.178270e+05,9.000000,0.000000,0.000000,40.000000
50%,37.000000,1.783560e+05,10.000000,0.000000,0.000000,40.000000
75%,48.000000,2.370510e+05,12.000000,0.000000,0.000000,45.000000
max,90.000000,1.484705e+06,16.000000,99999.000000,4356.000000,99.000000

In [16]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32561 entries, 0 to 32560
Data columns (total 15 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   age             32561 non-null  int64
 1   workclass       32561 non-null  object
 2   final-weight    32561 non-null  int64
 3   education       32561 non-null  object
 4   education-num   32561 non-null  int64
 5   marital-status  32561 non-null  object
 6   occupation      32561 non-null  object
 7   relationship    32561 non-null  object
 8   race            32561 non-null  object
 9   sex             32561 non-null  object
 10  capital-gain    32561 non-null  int64
 11  capital-loos    32561 non-null  int64
 12  hour-per-week   32561 non-null  int64
 13  native-country  32561 non-null  object
 14  income          32561 non-null  object
dtypes: int64(6), object(9)
memory usage: 3.7+ MB

In [17]:
dataset.tail()

,age,workclass,final-weight,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loos,hour-per-week,native-country,income
32556,27,Private,257302,Assoc-acdm,12,Married-civ-spouse,Tech-support,Wife,White,Female,0,0,38,United-States,<=50K
32557,40,Private,154374,HS-grad,9,Married-civ-spouse,Machine-op-inspct,Husband,White,Male,0,0,40,United-States,>50K
32558,58,Private,151910,HS-grad,9,Widowed,Adm-clerical,Unmarried,White,Female,0,0,40,United-States,<=50K
32559,22,Private,201490,HS-grad,9,Never-married,Adm-clerical,Own-child,White,Male,0,0,20,United-States,<=50K
32560,52,Self-emp-inc,287927,HS-grad,9,Married-civ-spouse,Exec-managerial,Wife,White,Female,15024,0,40,United-States,>50K

## Amostragem Aleatoria Simple

In [18]:
df_amostragem_aleatoria_simple = dataset.sample(n=100, random_state=2)

In [19]:
df_amostragem_aleatoria_simple.shape

(100, 15)

In [20]:
df_amostragem_aleatoria_simple.head()

,age,workclass,final-weight,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loos,hour-per-week,native-country,income
16054,42,State-gov,160369,HS-grad,9,Never-married,Protective-serv,Not-in-family,White,Male,0,0,40,United-States,>50K
32382,44,Local-gov,150171,HS-grad,9,Divorced,Adm-clerical,Unmarried,White,Female,0,0,40,United-States,<=50K
10749,39,Local-gov,256997,Bachelors,13,Married-civ-spouse,Craft-repair,Husband,White,Male,0,0,40,United-States,<=50K
15377,39,Private,147548,HS-grad,9,Married-civ-spouse,Craft-repair,Husband,White,Male,0,0,40,United-States,<=50K
29660,29,Federal-gov,106179,Some-college,10,Never-married,Prof-specialty,Not-in-family,White,Female,0,1408,40,United-States,<=50K

In [21]:
df_amostragem_aleatoria_simple.tail()

,age,workclass,final-weight,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loos,hour-per-week,native-country,income
24290,72,Federal-gov,94242,Some-college,10,Widowed,Tech-support,Not-in-family,White,Female,0,0,16,United-States,<=50K
6286,24,Private,138938,Some-college,10,Divorced,Adm-clerical,Not-in-family,White,Female,0,0,40,United-States,<=50K
8138,52,Self-emp-not-inc,162381,HS-grad,9,Divorced,Sales,Not-in-family,White,Male,0,0,40,United-States,<=50K
9775,22,Private,416165,Some-college,10,Never-married,Sales,Unmarried,White,Female,0,0,32,United-States,<=50K
29083,53,Private,187356,Some-college,10,Married-civ-spouse,Craft-repair,Husband,White,Male,0,0,66,United-States,<=50K

In [22]:
def amostragem_aleatoria_simples(dataset, amostras):
    return dataset.sample(n = amostras, random_state=1)

In [23]:
df_amostra_aleatoria_simples = amostragem_aleatoria_simples(dataset, 100)
df_amostra_aleatoria_simples.shape

(100, 15)

df_amostra_aleatoria_simples.head()

## Amostragem Sistemática

In [24]:
random.seed(1)
random.randint(0,325)

68

In [25]:
np.arange(68, len(dataset), step = 325)

array([   68,   393,   718,  1043,  1368,  1693,  2018,  2343,  2668,
        2993,  3318,  3643,  3968,  4293,  4618,  4943,  5268,  5593,
        5918,  6243,  6568,  6893,  7218,  7543,  7868,  8193,  8518,
        8843,  9168,  9493,  9818, 10143, 10468, 10793, 11118, 11443,
       11768, 12093, 12418, 12743, 13068, 13393, 13718, 14043, 14368,
       14693, 15018, 15343, 15668, 15993, 16318, 16643, 16968, 17293,
       17618, 17943, 18268, 18593, 18918, 19243, 19568, 19893, 20218,
       20543, 20868, 21193, 21518, 21843, 22168, 22493, 22818, 23143,
       23468, 23793, 24118, 24443, 24768, 25093, 25418, 25743, 26068,
       26393, 26718, 27043, 27368, 27693, 28018, 28343, 28668, 28993,
       29318, 29643, 29968, 30293, 30618, 30943, 31268, 31593, 31918,
       32243])

In [26]:
def amostragem_sistematica(dataset, amostras):
    intervalo = len(dataset) // amostras
    random.seed(1)
    inicio = random.randint(0,intervalo)
    indices = np.arange(inicio, len(dataset),step = intervalo)
    amostra_stsematica = dataset.iloc[indices]
    return amostra_stsematica

In [27]:
df_amostragem_sistematica = amostragem_sistematica(dataset, 100)
df_amostragem_sistematica.shape

(100, 15)

In [28]:
df_amostragem_sistematica.head()

,age,workclass,final-weight,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loos,hour-per-week,native-country,income
68,49,Self-emp-inc,191681,Some-college,10,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,50,United-States,>50K
393,34,State-gov,98101,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,7688,0,45,?,>50K
718,22,Private,214399,Some-college,10,Never-married,Sales,Own-child,White,Female,0,0,15,United-States,<=50K
1043,44,Private,167005,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,7688,0,60,United-States,>50K
1368,52,Private,152234,HS-grad,9,Married-civ-spouse,Exec-managerial,Husband,Asian-Pac-Islander,Male,99999,0,40,Japan,>50K

## Amostragem Por Grupos

In [29]:
len(dataset) // 10

3256

In [30]:
grupos = []
contagem = 0
id_grupo = 0
for _ in dataset.iterrows():
    grupos.append(id_grupo)
    contagem += 1
    if contagem > 3256:
        contagem = 0
        id_grupo += 1

In [31]:
np.unique(grupos, return_counts=True)

(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
 array([3257, 3257, 3257, 3257, 3257, 3257, 3257, 3257, 3257, 3248]))

In [32]:
np.shape(grupos), dataset.shape

((32561,), (32561, 15))

In [33]:
dataset['grupo'] = grupos

In [34]:
dataset.head()

,age,workclass,final-weight,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loos,hour-per-week,native-country,income,grupo
0,39,State-gov,77516,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States,<=50K,0
1,50,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,<=50K,0
2,38,Private,215646,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,<=50K,0
3,53,Private,234721,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States,<=50K,0
4,28,Private,338409,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40,Cuba,<=50K,0

In [35]:
dataset.tail()

,age,workclass,final-weight,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loos,hour-per-week,native-country,income,grupo
32556,27,Private,257302,Assoc-acdm,12,Married-civ-spouse,Tech-support,Wife,White,Female,0,0,38,United-States,<=50K,9
32557,40,Private,154374,HS-grad,9,Married-civ-spouse,Machine-op-inspct,Husband,White,Male,0,0,40,United-States,>50K,9
32558,58,Private,151910,HS-grad,9,Widowed,Adm-clerical,Unmarried,White,Female,0,0,40,United-States,<=50K,9
32559,22,Private,201490,HS-grad,9,Never-married,Adm-clerical,Own-child,White,Male,0,0,20,United-States,<=50K,9
32560,52,Self-emp-inc,287927,HS-grad,9,Married-civ-spouse,Exec-managerial,Wife,White,Female,15024,0,40,United-States,>50K,9

In [36]:
random.randint(0,9)

9

In [37]:
df_agrupamento = dataset[dataset['grupo'] ==  random.randint(0,9)]
df_agrupamento.shape

(3257, 16)

In [38]:
df_agrupamento['grupo'].value_counts()

grupo
1    3257
Name: count, dtype: int64

In [39]:
df_agrupamento.head()

,age,workclass,final-weight,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loos,hour-per-week,native-country,income,grupo
3257,31,Private,207537,HS-grad,9,Divorced,Craft-repair,Own-child,White,Male,0,1669,50,United-States,<=50K,1
3258,19,Private,417657,HS-grad,9,Never-married,Handlers-cleaners,Own-child,White,Male,0,0,50,United-States,<=50K,1
3259,45,Private,189890,Assoc-acdm,12,Divorced,Prof-specialty,Unmarried,White,Female,5455,0,38,United-States,<=50K,1
3260,34,Private,223212,Bachelors,13,Married-civ-spouse,Prof-specialty,Husband,White,Male,0,1848,40,Peru,>50K,1
3261,26,Private,108658,HS-grad,9,Never-married,Craft-repair,Not-in-family,White,Male,0,0,40,United-States,<=50K,1

In [40]:
def amostragem_agrupamento(dataset, numero_grupos):
    intervalo = len(dataset) / numero_grupos

    grupos = []
    id_grupo = 0
    contagem = 0
    for _ in dataset.iterrows():
        grupos.append(id_grupo)
        contagem += 1
        if contagem > intervalo:
            contagem = 0
            id_grupo += 1
    dataset['grupo'] = grupos 
    grupo_sorteado = random.randint(0,numero_grupos)
    return dataset[dataset['grupo'] == grupo_sorteado]

In [41]:
df_amostras_agrupamento = amostragem_agrupamento(dataset, 100)

In [42]:
df_amostras_agrupamento.head()

,age,workclass,final-weight,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loos,hour-per-week,native-country,income,grupo
10432,22,Self-emp-inc,150683,HS-grad,9,Never-married,Machine-op-inspct,Own-child,White,Male,0,0,24,United-States,<=50K,32
10433,27,Private,207611,HS-grad,9,Never-married,Other-service,Not-in-family,White,Female,0,0,52,United-States,<=50K,32
10434,45,State-gov,319666,Prof-school,15,Divorced,Prof-specialty,Unmarried,White,Female,0,0,43,United-States,<=50K,32
10435,39,Private,155961,HS-grad,9,Divorced,Adm-clerical,Unmarried,Black,Female,0,0,38,United-States,<=50K,32
10436,25,Local-gov,117833,Bachelors,13,Never-married,Prof-specialty,Not-in-family,White,Female,0,0,35,United-States,<=50K,32

## Amostra Estratificada

- População: 90 Pessoas 
- 64 mulhres e 36 homens
- Amostragem de 10% da população: 90 pessoas 
- Mulheres representam 60% da população 
- Homens representam 40% da população 
- Quantidade de Mulhres
     54*10/100 = 5,4(arrendamos para 5)
- Quantidade de Homens
     36*10/100 = 3,6(arrendamos para 4)
- Cáculos para saber quantos elementos de cada grupo devem ser selecionados. Utilizar na sequência outra técnica para seleção das amostras.

In [43]:
from sklearn.model_selection import StratifiedShuffleSplit

In [44]:
dataset['income'].value_counts()

income
<=50K    24720
>50K      7841
Name: count, dtype: int64

In [45]:
7841 / len(dataset), 24720 / len(dataset)

(0.2408095574460244, 0.7591904425539756)

In [46]:
100 / len(dataset)

0.0030711587481956942

In [47]:
split = StratifiedShuffleSplit(test_size=0.0030711587481956942)
for x, y in split.split(dataset, dataset['income']):
    df_x = dataset.iloc[x]
    df_y = dataset.iloc[y]

In [48]:
df_x.shape, df_y.shape

((32461, 16), (100, 16))

In [49]:
df_y.head()

,age,workclass,final-weight,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loos,hour-per-week,native-country,income,grupo
4046,23,Private,291248,HS-grad,9,Never-married,Machine-op-inspct,Other-relative,Black,Male,0,0,40,United-States,<=50K,12
12960,37,Local-gov,117760,Assoc-voc,11,Never-married,Protective-serv,Not-in-family,White,Male,4650,0,40,United-States,<=50K,39
30544,24,Private,118023,Some-college,10,Never-married,Handlers-cleaners,Own-child,White,Male,0,0,30,United-States,<=50K,93
5539,21,Self-emp-inc,265116,Some-college,10,Never-married,Exec-managerial,Not-in-family,White,Male,0,0,40,United-States,<=50K,16
848,39,Private,138192,Bachelors,13,Married-civ-spouse,Craft-repair,Husband,White,Male,0,0,40,United-States,<=50K,2

In [50]:
df_y['income'].value_counts()

income
<=50K    76
>50K     24
Name: count, dtype: int64

In [51]:
def amostragem_estratificada(dataset, percentual):
    split = StratifiedShuffleSplit(test_size=percentual, random_state=1)
    for _, y in split.split(dataset, dataset['income']):
        df_y = dataset.iloc[y]
    return df_y

In [52]:
df_amostra_estratificada = amostragem_estratificada(dataset, 0.0030711587481956942)
df_amostra_estratificada.shape

(100, 16)

## Amostra de Reservatorio

In [60]:
def amostragem_reservatorio(dataset, amostras):
    stream = []
    for i in range(len(dataset)):
        stream.append(i)

    i = 0
    tamanho = len(dataset)

    reservatorio = [0] * amostras
    for i in range(amostras):
        reservatorio[i] = stream[i]

    while i < tamanho:
        j = random.randrange(i + 1)
        if j < amostras:
            reservatorio[j] = stream[i]
        i += 1
    return dataset.iloc[reservatorio]

In [61]:
df_amostragem_reservatorio = amostragem_reservatorio(dataset, 100)
df_amostragem_reservatorio.shape

(100, 16)

In [62]:
df_amostragem_reservatorio.head()

,age,workclass,final-weight,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loos,hour-per-week,native-country,income,grupo
29608,41,Self-emp-inc,114580,Prof-school,15,Married-civ-spouse,Exec-managerial,Wife,White,Female,0,2415,55,United-States,>50K,90
21696,37,Federal-gov,329088,HS-grad,9,Married-civ-spouse,Adm-clerical,Husband,Black,Male,0,0,40,United-States,<=50K,66
30676,42,Private,355728,Assoc-voc,11,Never-married,Craft-repair,Not-in-family,White,Male,0,0,44,United-States,<=50K,94
28550,43,Private,110970,Bachelors,13,Married-civ-spouse,Prof-specialty,Husband,White,Male,0,1902,40,United-States,>50K,87
8768,52,Federal-gov,221532,Bachelors,13,Married-civ-spouse,Protective-serv,Husband,White,Male,0,0,45,United-States,>50K,26

## Comparativo dos Resultados

In [54]:
dataset['age'].mean()

np.float64(38.58164675532078)

In [55]:
df_amostra_aleatoria_simples['age'].mean()

np.float64(39.41)

In [56]:
df_amostragem_sistematica['age'].mean()

np.float64(37.57)

In [58]:
df_amostras_agrupamento['age'].mean()

np.float64(38.57361963190184)

In [63]:
df_amostragem_reservatorio['age'].mean()

np.float64(38.18)